# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Weather(object):
    def setupUi(self, Weather):
        Weather.setObjectName("Weather")
        Weather.resize(180, 265)
        Weather.setMaximumSize(QtCore.QSize(180, 265))
        Weather.setMouseTracking(False)
        Weather.setTabletTracking(False)
        Weather.setStyleSheet("")
        self.measure = QtWidgets.QPushButton(Weather)
        self.measure.setGeometry(QtCore.QRect(120, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(15)
        self.measure.setFont(font)
        self.measure.setStyleSheet("\n"
"background-color:rgba(255, 255, 255, 0);")
        self.measure.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../FIFA/5332623571548329962-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.measure.setIcon(icon)
        self.measure.setIconSize(QtCore.QSize(35, 35))
        self.measure.setObjectName("measure")
        self.widget = QtWidgets.QWidget(Weather)
        self.widget.setGeometry(QtCore.QRect(0, 0, 180, 265))
        self.widget.setStyleSheet("#widget{\n"
"background-color:rgba(213, 213, 213,180);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"        border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}")
        self.widget.setObjectName("widget")
        self.Time = QtWidgets.QWidget(self.widget)
        self.Time.setGeometry(QtCore.QRect(0, 0, 180, 30))
        self.Time.setStyleSheet("background-color: None;")
        self.Time.setObjectName("Time")
        self.dayofweek = QtWidgets.QLabel(self.Time)
        self.dayofweek.setGeometry(QtCore.QRect(5, 5, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.dayofweek.setFont(font)
        self.dayofweek.setText("")
        self.dayofweek.setObjectName("dayofweek")
        self.day = QtWidgets.QLabel(self.Time)
        self.day.setGeometry(QtCore.QRect(67, 6, 45, 20))
        font = QtGui.QFont()
        font.setFamily("TechnicBold")
        font.setPointSize(10)
        self.day.setFont(font)
        self.day.setStyleSheet("QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}\n"
"#day::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}")
        self.day.setText("")
        self.day.setObjectName("day")
        self.line = QtWidgets.QFrame(self.Time)
        self.line.setGeometry(QtCore.QRect(110, 5, 15, 20))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dayam = QtWidgets.QLabel(self.Time)
        self.dayam.setGeometry(QtCore.QRect(125, 6, 45, 20))
        font = QtGui.QFont()
        font.setFamily("TechnicBold")
        font.setPointSize(10)
        self.dayam.setFont(font)
        self.dayam.setStyleSheet("QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}\n"
"#dayam::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}")
        self.dayam.setText("")
        self.dayam.setObjectName("dayam")
        self.line_17 = QtWidgets.QFrame(self.widget)
        self.line_17.setGeometry(QtCore.QRect(15, 25, 150, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.temperature = QtWidgets.QLabel(self.widget)
        self.temperature.setGeometry(QtCore.QRect(60, 40, 60, 50))
        font = QtGui.QFont()
        font.setFamily("TechnicLite")
        font.setPointSize(30)
        self.temperature.setFont(font)
        self.temperature.setStyleSheet("")
        self.temperature.setText("")
        self.temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature.setObjectName("temperature")
        self.temperature_state = QtWidgets.QLabel(self.widget)
        self.temperature_state.setGeometry(QtCore.QRect(70, 90, 40, 40))
        self.temperature_state.setStyleSheet("QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}\n"
"#temperature_state::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color:rgb(255, 255, 255);\n"
"}")
        self.temperature_state.setText("")
        self.temperature_state.setScaledContents(True)
        self.temperature_state.setObjectName("temperature_state")
        self.city = QtWidgets.QLineEdit(self.widget)
        self.city.setGeometry(QtCore.QRect(0, 130, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.city.setFont(font)
        self.city.setStyleSheet("#city{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"}\n"
"#city:hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"#city::pressed{\n"
"    background-color:rgba(172, 255, 10);\n"
"}")
        self.city.setText("")
        self.city.setAlignment(QtCore.Qt.AlignCenter)
        self.city.setObjectName("city")
        self.wind = QtWidgets.QWidget(self.widget)
        self.wind.setGeometry(QtCore.QRect(8, 170, 42, 40))
        self.wind.setStyleSheet("#wind:hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}\n"
"QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}")
        self.wind.setObjectName("wind")
        self.picwind = QtWidgets.QLabel(self.wind)
        self.picwind.setGeometry(QtCore.QRect(10, 1, 20, 20))
        self.picwind.setText("")
        self.picwind.setPixmap(QtGui.QPixmap("icon/wind.png"))
        self.picwind.setScaledContents(True)
        self.picwind.setObjectName("picwind")
        self.wind1 = QtWidgets.QLabel(self.wind)
        self.wind1.setGeometry(QtCore.QRect(-1, 18, 41, 20))
        font = QtGui.QFont()
        font.setFamily("TechnicLite")
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.wind1.setFont(font)
        self.wind1.setText("")
        self.wind1.setAlignment(QtCore.Qt.AlignCenter)
        self.wind1.setWordWrap(False)
        self.wind1.setObjectName("wind1")
        self.humidity_W = QtWidgets.QWidget(self.widget)
        self.humidity_W.setGeometry(QtCore.QRect(50, 170, 40, 40))
        self.humidity_W.setStyleSheet("#humidity_W:hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}\n"
"QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}")
        self.humidity_W.setObjectName("humidity_W")
        self.humidity = QtWidgets.QLabel(self.humidity_W)
        self.humidity.setGeometry(QtCore.QRect(0, 18, 40, 20))
        font = QtGui.QFont()
        font.setFamily("TechnicLite")
        font.setPointSize(10)
        self.humidity.setFont(font)
        self.humidity.setMouseTracking(True)
        self.humidity.setText("")
        self.humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity.setObjectName("humidity")
        self.pichumidity = QtWidgets.QLabel(self.humidity_W)
        self.pichumidity.setGeometry(QtCore.QRect(11, 3, 16, 16))
        self.pichumidity.setText("")
        self.pichumidity.setPixmap(QtGui.QPixmap("icon/water.png"))
        self.pichumidity.setScaledContents(True)
        self.pichumidity.setObjectName("pichumidity")
        self.UVI_w = QtWidgets.QWidget(self.widget)
        self.UVI_w.setGeometry(QtCore.QRect(90, 170, 40, 40))
        self.UVI_w.setStyleSheet("#UVI_w:hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}\n"
"QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}")
        self.UVI_w.setObjectName("UVI_w")
        self.UVI = QtWidgets.QLabel(self.UVI_w)
        self.UVI.setGeometry(QtCore.QRect(0, 18, 40, 20))
        font = QtGui.QFont()
        font.setFamily("TechnicLite")
        font.setPointSize(10)
        self.UVI.setFont(font)
        self.UVI.setMouseTracking(True)
        self.UVI.setText("")
        self.UVI.setAlignment(QtCore.Qt.AlignCenter)
        self.UVI.setObjectName("UVI")
        self.picUVi = QtWidgets.QLabel(self.UVI_w)
        self.picUVi.setGeometry(QtCore.QRect(9, 1, 20, 19))
        self.picUVi.setText("")
        self.picUVi.setPixmap(QtGui.QPixmap("icon/cs0.png"))
        self.picUVi.setScaledContents(True)
        self.picUVi.setObjectName("picUVi")
        self.suntime_W = QtWidgets.QWidget(self.widget)
        self.suntime_W.setGeometry(QtCore.QRect(130, 170, 43, 40))
        self.suntime_W.setStyleSheet("#suntime_W:hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}\n"
"QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}")
        self.suntime_W.setObjectName("suntime_W")
        self.suntime = QtWidgets.QLabel(self.suntime_W)
        self.suntime.setGeometry(QtCore.QRect(0, 18, 43, 20))
        font = QtGui.QFont()
        font.setFamily("TechnicLite")
        font.setPointSize(10)
        self.suntime.setFont(font)
        self.suntime.setMouseTracking(True)
        self.suntime.setText("")
        self.suntime.setAlignment(QtCore.Qt.AlignCenter)
        self.suntime.setObjectName("suntime")
        self.picsun = QtWidgets.QLabel(self.suntime_W)
        self.picsun.setGeometry(QtCore.QRect(10, 1, 20, 20))
        self.picsun.setText("")
        self.picsun.setPixmap(QtGui.QPixmap("icon/sunrise.png"))
        self.picsun.setScaledContents(True)
        self.picsun.setObjectName("picsun")
        self.line_16 = QtWidgets.QFrame(self.widget)
        self.line_16.setGeometry(QtCore.QRect(15, 220, 150, 16))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setGeometry(QtCore.QRect(10, 230, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.temp = QtWidgets.QPushButton(self.widget)
        self.temp.setGeometry(QtCore.QRect(130, 50, 32, 32))
        self.temp.setStyleSheet("#temp{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#temp:hover{\n"
"    background-color:rgba(255, 255, 255,30);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}")
        self.temp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/C.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temp.setIcon(icon1)
        self.temp.setIconSize(QtCore.QSize(32, 32))
        self.temp.setObjectName("temp")
        self.picnec0 = QtWidgets.QLabel(self.widget)
        self.picnec0.setGeometry(QtCore.QRect(80, 237, 17, 17))
        self.picnec0.setStyleSheet("#picnec0::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}")
        self.picnec0.setText("")
        self.picnec0.setScaledContents(True)
        self.picnec0.setObjectName("picnec0")
        self.picnec1 = QtWidgets.QLabel(self.widget)
        self.picnec1.setGeometry(QtCore.QRect(100, 237, 17, 17))
        self.picnec1.setStyleSheet("QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}\n"
"#picnec1::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color:rgb(255, 255, 255);\n"
"}")
        self.picnec1.setText("")
        self.picnec1.setScaledContents(True)
        self.picnec1.setObjectName("picnec1")
        self.picnec2 = QtWidgets.QLabel(self.widget)
        self.picnec2.setGeometry(QtCore.QRect(120, 237, 17, 17))
        self.picnec2.setStyleSheet("QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}\n"
"#picnec2::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color:rgb(255, 255, 255);\n"
"}")
        self.picnec2.setText("")
        self.picnec2.setScaledContents(True)
        self.picnec2.setObjectName("picnec2")
        self.picnec3 = QtWidgets.QLabel(self.widget)
        self.picnec3.setGeometry(QtCore.QRect(140, 237, 17, 17))
        self.picnec3.setStyleSheet("QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}\n"
"#picnec3::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color:rgb(255, 255, 255);\n"
"}")
        self.picnec3.setText("")
        self.picnec3.setScaledContents(True)
        self.picnec3.setObjectName("picnec3")
        self.picnec4 = QtWidgets.QLabel(self.widget)
        self.picnec4.setGeometry(QtCore.QRect(160, 237, 17, 17))
        self.picnec4.setStyleSheet("QToolTip { \n"
"    background-color: rgb(213, 213, 213);\n"
"    border:rgba(172, 255, 218)}\n"
"#picnec4::hover{\n"
"    background-color:rgb(226, 226, 226);\n"
"    border-style: outset;\n"
"    border-width: 0.5px;\n"
"    border-color:rgb(255, 255, 255);\n"
"}")
        self.picnec4.setText("")
        self.picnec4.setScaledContents(True)
        self.picnec4.setObjectName("picnec4")
        self.reset = QtWidgets.QPushButton(self.widget)
        self.reset.setGeometry(QtCore.QRect(10, 40, 18, 18))
        self.reset.setStyleSheet("#reset{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#reset:hover{\n"
"    background-color:rgba(255, 255, 255,30);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-right-color:rgb(213, 213, 213);\n"
"    border-bottom-color:rgb(213, 213, 213)\n"
"}")
        self.reset.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon2)
        self.reset.setIconSize(QtCore.QSize(12, 12))
        self.reset.setObjectName("reset")

        self.retranslateUi(Weather)
        QtCore.QMetaObject.connectSlotsByName(Weather)

    def retranslateUi(self, Weather):
        _translate = QtCore.QCoreApplication.translate
        Weather.setWindowTitle(_translate("Weather", "Form"))
        self.label_1.setText(_translate("Weather", "Necessary:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Weather = QtWidgets.QWidget()
    ui = Ui_Weather()
    ui.setupUi(Weather)
    Weather.show()
    sys.exit(app.exec_())
